name: Run ETL

on:
  schedule: # all in UTC
    - cron: "0 6 * * *"
    - cron: "0 10 * * *"
    - cron: "0 12 * * *"
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: # for persistent artifact usage
  contents: write
  actions: read     

jobs:
  restore-parquet:
    runs-on: ubuntu-latest
    outputs:
      parquet-exists: ${{ steps.check.outputs.exists }}
    steps:
      - name: Try downloading parquet-store from previous run
        id: try
        uses: actions/download-artifact@v4
        with:
          name: parquet-store
          path: parquet-store
        continue-on-error: true

      - name: Check if downloaded
        id: check
        run: |
          if [ -d "parquet-store" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Create empty directory if not exists
        run: mkdir -p parquet-store

      - name: Upload workspace for next job
        uses: actions/upload-artifact@v4
        with:
          name: parquet-workspace
          path: parquet-store


  run-etl:
    runs-on: ubuntu-latest
    needs: restore-parquet

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Download restored parquet-store
        uses: actions/download-artifact@v4
        with:
          name: parquet-workspace
          path: .

      - name: Run ETL script
        env:
          BQ_SERVICE_ACCOUNT: ${{ secrets.BQ_SERVICE_ACCOUNT }}
        run: python main.py

      - name: Upload updated parquet-store
        uses: actions/upload-artifact@v4
        with:
          name: parquet-store
          path: parquet-store
          retention-days: 30

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "github-actions"

          git add docs
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Daily ETL update $(date)"
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:main
          fi
